# This is a basic workflow to connect remotely to a machine via ssh and pull the changes
name: remote ssh git pull
on: [push]
jobs:

  build:
    name: connect and pull
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh pull
      uses: appleboy/ssh-action@master
      env:
        REPO_PATH: "/var/www/ci_test"
        REPO_NAME: ${{ github.event.repository.name }} 
      with:
        host: ${{ secrets.EASY_SERVER_HOST }}
        username: ${{ secrets.EASY_SERVER_USR }}
        password: ${{ secrets.EASY_SERVER_PWD }}
        envs: REPO_PATH, REPO_NAME
        script: |
          cd "$REPO_PATH/$REPO_NAME"
          git pull
